ccmlib/scylla_repository: use --packaging option, drop sed to prevent running systemctl
scylladb/scylla-ccm pull request #250
Opened 2020-10-12 10:18 UTC by syuu1228

To skip running systemctl in scylla-ccm, rewriting install.sh by sed can break
the script, we can use --packaging option instead.

Fixes #249

2020-10-12 11:00 UTC, syuu1228 commented
@fruch It looks like works with my local branch of https://github.com/scylladb/scylla/pull/7405.
But it does not compatible with latest next, we need to merge https://github.com/scylladb/scylla/pull/7405 first.
 
```
[syuu@monster scylla-ccm.3]$ ccm create scylla-reloc1 -n 1 --scylla --version temp --scylla-core-package-uri=/home/syuu/scylla.2/build/release/scylla-package.tar.gz --scylla-tools-java-package-uri=/home/syuu/scylla.2/tools/java/build/scylla-tools-package.tar.gz --scylla-jmx-package-uri=/home/syuu/scylla.2/tools/jmx/build/scylla-jmx-package.tar.gz
Extracting /home/syuu/scylla.2/build/release/scylla-package.tar.gz as version temp ...
Relocatable package format version 2 detected.
Extracting /home/syuu/scylla.2/tools/java/build/scylla-tools-package.tar.gz as version temp ...
Relocatable package format version 2 detected.
Extracting /home/syuu/scylla.2/tools/jmx/build/scylla-jmx-package.tar.gz as version temp ...
Relocatable package format version 2 detected.
Scylla non-root install completed.
Current cluster is now: scylla-reloc1
```

But this change requires

2020-10-12 11:24 UTC, fruch commented
> @fruch It looks like works with my local branch of [scylladb/scylla#7405](https://github.com/scylladb/scylla/pull/7405).
> But it does not compatible with latest next, we need to merge [scylladb/scylla#7405](https://github.com/scylladb/scylla/pull/7405) first.
> 
> ```
> [syuu@monster scylla-ccm.3]$ ccm create scylla-reloc1 -n 1 --scylla --version temp --scylla-core-package-uri=/home/syuu/scylla.2/build/release/scylla-package.tar.gz --scylla-tools-java-package-uri=/home/syuu/scylla.2/tools/java/build/scylla-tools-package.tar.gz --scylla-jmx-package-uri=/home/syuu/scylla.2/tools/jmx/build/scylla-jmx-package.tar.gz
> Extracting /home/syuu/scylla.2/build/release/scylla-package.tar.gz as version temp ...
> Relocatable package format version 2 detected.
> Extracting /home/syuu/scylla.2/tools/java/build/scylla-tools-package.tar.gz as version temp ...
> Relocatable package format version 2 detected.
> Extracting /home/syuu/scylla.2/tools/jmx/build/scylla-jmx-package.tar.gz as version temp ...
> Relocatable package format version 2 detected.
> Scylla non-root install completed.
> Current cluster is now: scylla-reloc1
> ```

can we version `install.sh` somehow ? so we can make the code in ccm backward compatible ? 
I would like that ccm would be able older version without a problem...

2020-10-14 07:56 UTC, penberg commented
> I would like that ccm would be able older version without a problem...

The problem is not in `install.sh`, but in ccm doing a string replacement on it. How would you go about versioning this...?

2020-10-14 16:21 UTC, syuu1228 commented
> can we version `install.sh` somehow ? so we can make the code in ccm backward compatible ?
> I would like that ccm would be able older version without a problem...

@fruch  We can use relocatable package format just like we did on tarball layout change.
So, package relocatable format v3 or later support to use `--packaging` option to skip systemctl.
I just pushed new version of the PR implementing this.

But before merging this, we need to ask @avikivity okay to continue merging,
because there were discussion to renaming the option name:
https://github.com/scylladb/scylla/pull/7405#issuecomment-707531233

@avikivity Do we want to rename `--packaging` first, or can we continue merging this with current option name?

2020-10-19 12:57 UTC, avikivity commented
Let's do the renaming later (and keep --packaging for compatibility).

2020-10-20 07:57 UTC, syuu1228 commented
@fruch Please review this again, if it looks okay I will send fixes on main repo side, and increment relocatable package version.

2020-10-20 08:01 UTC, fruch commented on ccmlib/scylla_repository.py
> +        core_version = download_version(version, verbose=verbose, url=url, target_dir=os.path.join(
why are you adding this ? I think the version is already part of the cdir, why adding it again ?

2020-10-20 08:02 UTC, fruch commented on ccmlib/scylla_repository.py
> +                package_version = int(f.read().strip())
should we consider using something like LooseVersion instead of int ? so later we could have things like `1.2` ?

2020-10-20 08:03 UTC, fruch commented on ccmlib/scylla_repository.py
> +        core_version = download_version(version, verbose=verbose, url=url, target_dir=os.path.join(
o.k, now I get it, should be named `package_version` like where it's used

2020-10-20 10:41 UTC, fruch requested changes
* s/core_version/package_version/
* we should consider not treating versions as int

2020-10-29 17:02 UTC, syuu1228 commented
@fruch rename core_version with package_version, switch to packaging.version to handle version number.
Since we stopped using int, change new version from 3 to 2.1.
Please review it again.

2020-10-29 20:52 UTC, fruch approved these changes
LGTM

2020-10-29 20:52 UTC, merged