ccmlib/scylla_repository: specify correct path to install.sh, drop sed
scylladb/scylla-ccm pull request #251
Opened 2020-10-12 13:09 UTC by syuu1228

We don't want to modify install.sh by sed since it may break the script,
specify correct path to install.sh and drop sed.

Related: #249
Related: scylladb/scylla#7405

2020-10-12 18:43 UTC, fruch commented
@syuu1228 as I've commented on #249, can we make this backward compatible ? so it won't break when using older versions of scylla ?

2020-10-12 18:44 UTC, fruch requested changes
Let's try to make it backward compatible, 
so older version can be used (for example formal 4.1/4.2 versions)

2020-10-12 18:45 UTC, fruch commented
@syuu1228 is this mean #250 can be closed ?

2020-11-05 13:04 UTC, fruch commented
@syuu1228 we can close this one, right ?

2020-11-06 15:26 UTC, syuu1228 commented
@fruch It different with #249, trying to drop `sed 's|"$prefix|"$root/$prefix|' -i install.sh` line, not systemctl one.

About versioning this fix, unlike #249, we don't really need versioning for this PR.
Because the result of the script should be identical with current implementation, also it doesn't require changes on install.sh of scylla.
But if you still prefer versioning this to make sure not to break anything, I'll increment pkg version to 2.2 for this change.

Note: rebased with latest next.

2020-12-30 06:57 UTC, fruch commented
> @fruch It different with #249, trying to drop `sed 's|"$prefix|"$root/$prefix|' -i install.sh` line, not systemctl one.
> 
> About versioning this fix, unlike #249, we don't really need versioning for this PR.
> Because the result of the script should be identical with current implementation, also it doesn't require changes on install.sh of scylla.
> But if you still prefer versioning this to make sure not to break anything, I'll increment pkg version to 2.2 for this change.
> 
> Note: rebased with latest next.

sorry, it's need a rebase again.
and yes I would rather be on the safe side with those kind of changes, not to break installation of previous version (since we are introducing new upgrade test the really on this code path)

2021-01-04 09:02 UTC, syuu1228 commented
Seems like b7251e3eeba80e183efcaf61133e218420e51921 already fixed same issue, closing.

2021-01-04 09:02 UTC, closed without merging