fix(scylla_repository): Fix link relactable_url_base
scylladb/scylla-ccm pull request #293
Opened 2021-01-20 10:12 UTC by aleksbykov

After move to new location usage:
$ SCYLLA_VERSION=unstable/master:2021-01-18T15%3A48%3A13Z ./scripts/run_test.sh
failed with error:

 File "/home/abykov/Projects/scylladb-project/scylla-ccm/ccmlib/scylla_repository.py", line 175, in setup
    tmp_download, 'scylla-core-package'))
  File "/home/abykov/Projects/scylladb-project/scylla-ccm/ccmlib/scylla_repository.py", line 289, in download_version
    download_file(url=url, target_path=target,verbose=verbose)
  File "/home/abykov/Projects/scylladb-project/scylla-ccm/ccmlib/utils/download.py", line 110, in download_file
    resp.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://s3.amazonaws.com/downloads.scylladb.com/relocatable/unstable/master/2021-01-18T19%3A16%3A39Z/scylla-package.tar.gz

fixed url to support new location

2021-01-20 14:16 UTC, fruch commented on ccmlib/scylla_repository.py
> +RELOCATABLE_URLS_BASE = 'https://s3.amazonaws.com/downloads.scylladb.com/{0}/scylla/{1}/relocatable/{2}'
and here the tests are failing cause of this:
https://pipelines.actions.githubusercontent.com/Skr9gsPHF36fOQIfbI2XOe5unbCvL0MwMs2LngoePJmtPl71Xx/_apis/pipelines/1/runs/61/signedlogcontent/3?urlExpires=2021-01-20T14%3A16%3A57.7976092Z&urlSigningMethod=HMACV1&urlSignature=V7ZNIra%2B7DcesuHvIyjCO5x1yH1TlbkWHUHAFI2%2BQF4%3D

2021-01-20 14:54 UTC, aleksbykov commented on ccmlib/scylla_repository.py
> +RELOCATABLE_URLS_BASE = 'https://s3.amazonaws.com/downloads.scylladb.com/{0}/scylla/{1}/relocatable/{2}'
Yes, already found that even our pytest for ccm failed if using old versions

2021-01-20 16:41 UTC, fruch commented on tests/test_scylla_repository.py
> +    def test_setup_unstable_master_new_url(self):
mark those new tests with
`@pytest.mark.skip("slow integration test")`

or mark this whole class, with that.

they are too long for the github actions to run them each time

2021-01-20 16:46 UTC, fruch commented on tests/test_scylla_repository.py
> +    def test_setup_unstable_master_new_url(self):
also one of those failed:
```
2021-01-20T16:43:08.8474441Z =================================== FAILURES ===================================
2021-01-20T16:43:08.8475550Z ___________ TestScyllaRepository.test_setup_unstable_master_old_url ____________
2021-01-20T16:43:08.8476862Z tests/test_scylla_repository.py:29: in test_setup_unstable_master_old_url
2021-01-20T16:43:08.8478639Z     assert version == '4.4.dev'
2021-01-20T16:43:08.8479808Z E   AssertionError: assert '3.0' == '4.4.dev'
2021-01-20T16:43:08.8480854Z E     - 4.4.dev
2021-01-20T16:43:08.8481531Z E     + 3.0
2021-01-20T16:43:08.8482741Z         cdir       = '/home/runner/.ccm/scylla-repository/unstable/master/2020-08-29T22_24_05Z'
2021-01-20T16:43:08.8484313Z         self       = <tests.test_scylla_repository.TestScyllaRepository object at 0x7f43f8a4fb80>
2021-01-20T16:43:08.8485691Z         version    = '3.0'
2021-01-20T16:43:08.8486920Z ----------------------------- Captured stdout call -----------------------------
2021-01-20T16:43:08.8487852Z 3.0
2021-01-20T16:43:08.8488980Z ------------------------------ Captured log call -------------------------------
```

2021-01-20 16:46 UTC, fruch requested changes
skip the slow integration tests

2021-01-20 16:53 UTC, aleksbykov commented
@fruch Done

2021-01-21 09:25 UTC, fruch approved these changes
LGTM

2021-01-21 09:25 UTC, merged